version: 0.2

phases:
  install:
    commands:
      - echo installing depencies
      - npm install
  build:
    commands:
      - echo testing started
      - npm run test:unit
      - echo building artifacts
      - npm run build
  post_build:
    commands:
      - aws s3 cp dist s3://positive-vs-negative-vue --recursive
      - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'dist*'