version: 0.2

phases:
  install:
    commands:
      - echo installing depencies
      - npm install
  build:
    commands:
      - echo testing started
      - npm run test:unit
      - echo building artifacts
      - npm run build
  artifacts:
    files:
      - '*'
    base-directory: 'dist'
